name = "apptly-website"
main = "dist/index.mjs"
compatibility_date = "2026-04-20"
compatibility_flags = ["nodejs_compat"]

# Expose the Worker on *.workers.dev for smoke tests.
workers_dev = true

# Generate a unique preview URL for every deployment.
preview_urls = true

[dev]
ip = "0.0.0.0"
port = 8788

[assets]
directory = "../../.output/public"
binding = "ASSETS"

# wrangler d1 create apptly-website-content
[[d1_databases]]
binding = "DB"
database_name = "apptly-website-content"
database_id = "827f6d7b-4b07-4986-ba61-2fd84a17717a"
preview_database_id = "local"
